Fix pip install for Hatch
LibreTranslate recently switched to the Hatch build system
which doesn't seem to support installing in editable mode.
I'm removing the -e option from pip install to fix this
which isn't necessary unless users want to modify the source
after installing.

https://github.com/argosopentech/LibreTranslate-init/issues/17

Error before this commit:

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/libretranslate/LibreTranslate
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)